import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import LeftPane from "../components/LeftPane";
import RightPane from "../components/RightPane";

const Home: NextPage = () => {
    const router = useRouter();
    return (
        <div className="grid min-h-screen w-full grid-cols-1 items-center justify-center gap-10 text-gray-700 md:grid-cols-2 lg:grid-cols-3">
            {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
            <LeftPane />
            <RightPane router={router} />
        </div>
    );
};

export default Home;
